package com.orbital.run.domain.models

import java.time.Duration
import java.time.Instant

/**
 * User's athletic profile for training plan generation.
 *
 * Contains physiological data, current fitness level, and race goals.
 * All calculations use modern types for safety and clarity.
 *
 * @property age Athlete's age in years
 * @property gender Biological gender for VO2max calculations
 * @property weight Body weight in kilograms
 * @property restingHeartRate Resting HR in beats per minute
 * @property currentWeeklyDistance Current training volume
 * @property raceGoal Target race information
 */
data class UserProfile(
    val age: Int,
    val gender: Gender,
    val weight: Weight,
    val restingHeartRate: Int,
    val currentWeeklyDistance: Distance,
    val raceGoal: RaceGoal
) {
    /**
     * Calculate weeks from now to race date.
     */
    val weeksUntilRace: Int
        get() {
            val now = Instant.now()
            val durationUntilRace = java.time.Duration.between(now, raceGoal.raceDate)
            return (durationUntilRace.toDays() / 7).toInt().coerceAtLeast(1)
        }
    
    /**
     * Target pace to achieve race goal.
     */
    val targetPace: Duration
        get() {
            val secondsPerKm = (raceGoal.targetDuration.seconds / raceGoal.distance.kilometers).toLong()
            return Duration.ofSeconds(secondsPerKm)
        }
    
    /**
     * Target speed in km/h.
     */
    val targetSpeed: Double
        get() {
            val hoursDecimal = raceGoal.targetDuration.seconds / 3600.0
            return raceGoal.distance.kilometers / hoursDecimal
        }
}

/**
 * Goal for a specific race.
 */
data class RaceGoal(
    val distance: Distance,
    val targetDuration: Duration,
    val raceDate: Instant
)

/**
 * Biological gender for physiological calculations.
 */
enum class Gender(val displayName: String) {
    MALE("Homme"),
    FEMALE("Femme")
}

/**
 * Weight value object with type safety.
 */
data class Weight(val kilograms: Double) {
    val pounds: Double
        get() = kilograms * 2.20462
    
    companion object {
        fun fromPounds(lbs: Double) = Weight(lbs / 2.20462)
    }
}

/**
 * Complete training plan with physiological zones and weekly structure.
 *
 * Generated by OrbitalAlgorithm based on UserProfile.
 *
 * @property userProfile Source profile
 * @property physiologyMetrics Calculated VO2max, VMA, FCM, etc.
 * @property trainingZones HR, speed, and power zones for training
 * @property weeklySchedule Ordered list of training weeks
 * @property racePredictions Estimated finish times for various distances
 */
data class TrainingPlan(
    val id: String,
    val createdAt: Instant,
    val userProfile: UserProfile,
    val physiologyMetrics: PhysiologyMetrics,
    val trainingZones: TrainingZones,
    val weeklySchedule: List<TrainingWeek>,
    val racePredictions: List<RacePrediction>,
    val title: String = "Mon Plan",
    val goal: String = "" // e.g., "10km en 45 minutes"
) {
    /**
     * Total program distance (sum of all weeks).
     */
    val totalDistance: Distance
        get() = Distance(weeklySchedule.sumOf { it.totalDistance.meters })
    
    /**
     * Peak weekly volume (highest week).
     */
    val peakVolume: Distance
        get() = Distance(weeklySchedule.maxOf { it.totalDistance.meters })
}

/**
 * Physiological metrics calculated from user profile.
 *
 * @property maxHeartRate Maximum heart rate (FCM)
 * @property vma Maximal aerobic velocity (km/h)
 * @property vo2max VO2 max (ml/kg/min)
 * @property safeWeeklyVolume Conservative weekly distance
 * @property performanceWeeklyVolume Ambitious weekly distance
 * @property phaseDurations Duration of each training phase (base, build, taper)
 */
data class PhysiologyMetrics(
    val maxHeartRate: Int,
    val vma: Double,
    val vo2max: Double,
    val safeWeeklyVolume: Distance,
    val performanceWeeklyVolume: Distance,
    val phaseDurations: PhaseDurations
)

/**
 * Duration of each training phase in weeks.
 */
data class PhaseDurations(
    val basePhaseWeeks: Int,
    val buildPhaseWeeks: Int,
    val taperPhaseWeeks: Int
) {
    val totalWeeks: Int
        get() = basePhaseWeeks + buildPhaseWeeks + taperPhaseWeeks
}

/**
 * Training zones for HR, speed, and power.
 */
data class TrainingZones(
    val heartRateZones: List<HeartRateZone>,
    val speedZones: List<SpeedZone>,
    val powerZones: List<PowerZone>
)

/**
 * Heart rate training zone.
 */
data class HeartRateZone(
    val zone: Int,
    val name: String,
    val minBpm: Int,
    val maxBpm: Int,
    val description: String
)

/**
 * Speed/pace training zone.
 */
data class SpeedZone(
    val zone: Int,
    val name: String,
    val minSpeedKmh: Double,
    val maxSpeedKmh: Double,
    val minPaceSeconds: Int, // Seconds per km
    val maxPaceSeconds: Int
)

/**
 * Power training zone (cycling/running with power meter).
 */
data class PowerZone(
    val zone: Int,
    val name: String,
    val minWatts: Int,
    val maxWatts: Int,
    val description: String
)

/**
 * Predicted race time for a specific distance.
 */
data class RacePrediction(
    val distance: Distance,
    val predictedDuration: Duration
) {
    val predictedPace: Duration
        get() {
            val secondsPerKm = (predictedDuration.seconds / distance.kilometers).toLong()
            return Duration.ofSeconds(secondsPerKm)
        }
}

/**
 * One week of training in a plan.
 *
 * @property weekNumber Week index (1-based)
 * @property phase Training phase (base, build, peak, taper)
 * @property totalDistance Sum of all workout distances this week
 * @property workouts Ordered list of workouts (usually 4-6)
 */
data class TrainingWeek(
    val weekNumber: Int,
    val phase: TrainingPhase,
    val totalDistance: Distance,
    val workouts: List<PlannedWorkout>
) {
    /**
     * Start date of this week (calculated from race date).
     */
    fun startDate(raceDate: Instant): Instant {
        val weeksBeforeRace = weekNumber - 1 // Week 1 is N weeks before race
        val daysOffset = weeksBeforeRace * 7L
        return raceDate.minusSeconds(daysOffset * 24 * 60 * 60)
    }
}

/**
 * Training phase in periodization.
 */
enum class TrainingPhase(val displayName: String, val color: String) {
    BASE("Phase de base", "#4CAF50"),
    BUILD("Phase de développement", "#2196F3"),
    PEAK("Phase intensive", "#FF9800"),
    TAPER("Affûtage", "#9C27B0"),
    RECOVERY("Récupération", "#607D8B");
    
    val isHardPhase: Boolean
        get() = this in setOf(BUILD, PEAK)
}

/**
 * Planned workout (not yet completed).
 *
 * Differs from Activity (completed workout) in that it's prescriptive, not descriptive.
 * Contains target zones and prescribed structure, not actual metrics.
 */
data class PlannedWorkout(
    val type: ActivityType,
    val title: String,
    val targetDistance: Distance?,
    val targetDuration: Duration?,
    val structure: List<WorkoutInterval>
)

/**
 * Individual interval/step within a workout.
 *
 * @property description Human-readable description (e.g., "Échauffement", "5x1000m")
 * @property target What to aim for (distance, duration, or open-ended)
 * @property intensity Target zone or pace
 */
data class WorkoutInterval(
    val description: String,
    val target: IntervalTarget,
    val intensity: IntervalIntensity
)

/**
 * What to target for an interval.
 */
sealed class IntervalTarget {
    data class Distance(val meters: Double) : IntervalTarget()
    data class Duration(val duration: java.time.Duration) : IntervalTarget()
    object OpenEnded : IntervalTarget()
}

/**
 * How hard to work during an interval.
 */
sealed class IntervalIntensity {
    data class Zone(val zoneNumber: Int) : IntervalIntensity()
    data class Pace(val secondsPerKm: Int) : IntervalIntensity()
    object Recovery : IntervalIntensity()
}
